name = "mythic-data-queue-consumer"
main = "src/index.js"
compatibility_date = "2024-03-20"

[vars]
# Environment variables will be added here

##[[queues.consumers]]
##queue = "crm-events"
##max_batch_size = 10
##max_batch_timeout = 30

[[queues.consumers]]
queue = "events"
max_batch_size = 100
max_batch_timeout = 30 