name = "posthog-proxy"
main = "src/worker.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "p.mythicdata.io", custom_domain = true }
]

[[kv_namespaces]]
binding = "LOCATION_PERMISSIONS"
id = "a0ce6968118e487891252df2474e4eba"

[vars]
SUPABASE_URL="https://ggjpdbelozvvmxezdyrs.supabase.co"
# SUPABASE_KEY is stored as a secret
# Use: wrangler secret put SUPABASE_KEY